package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

import controller.ListeDesProjetsController;

import javax.swing.JLabel;
import javax.swing.JTable;

import java.awt.Color;
import javax.swing.JButton;
import java.awt.SystemColor;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class ListeDesProjets extends javax.swing.JFrame {

	ListeDesProjetsController controller;
	public JButton btnNouveauProjet;
	
    /**
     * Creates new form NewJFrame
     */
    public ListeDesProjets() {
        initComponents();
        controller = new ListeDesProjetsController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
            		"Nom du projet :", "Propose par :", "Objectif:" , "Estimation du Budget(MAD) :" , "Validation du chef" , "Validation du budget"
            }
        ){
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		return false;
        	}
        });
        jScrollPane1.setViewportView(jTable1);
        
        JLabel lblListeDesProjets = new JLabel("Liste des projets");
        lblListeDesProjets.setBackground(new Color(230, 230, 250));
        lblListeDesProjets.setFont(new Font("Trebuchet MS", Font.ITALIC, 19));
        
        btnNouveauProjet = new JButton("Nouveau Projet");
        btnNouveauProjet.setBackground(SystemColor.activeCaption);
        btnNouveauProjet.setForeground(new Color(255, 255, 255));
        btnNouveauProjet.setFont(new Font("Calibri", Font.BOLD, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(42)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 843, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(360)
        					.addComponent(lblListeDesProjets, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(399)
        					.addComponent(btnNouveauProjet)))
        			.addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addComponent(lblListeDesProjets)
        			.addGap(26)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 229, GroupLayout.PREFERRED_SIZE)
        			.addGap(47)
        			.addComponent(btnNouveauProjet)
        			.addContainerGap(54, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeDesProjets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeDesProjets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeDesProjets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeDesProjets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeDesProjets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration              
    
    public JTable getTable(){
    	return jTable1;
    }
}
